jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

-     - name: Restore dependencies
-       run: dotnet restore src/MoodBloom/MoodBloom.vbproj
+     - name: Restore all projects
+       run: dotnet restore src/MoodBloom.sln

-     - name: Build
-       run: dotnet build src/MoodBloom/MoodBloom.vbproj --configuration Release --no-restore
+     - name: Build solution
+       run: dotnet build src/MoodBloom.sln --configuration Release

-     - name: Test
-       run: dotnet test tests/MoodBloom.Tests/MoodBloom.Tests.vbproj --configuration Release --no-build
+     - name: Run tests
+       run: dotnet test src/MoodBloom.sln --configuration Release --no-build
